# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.


# Basic Site Settings
locale                   : "id-ID"
site_theme               : "default" # The available themes options are "default", "air", "sunrise", "mint", "dirt" and "contrast"
title                    : "Romano Emmanuelle"
title_separator          : "-"
name                     : &name "Romano Emmanuelle"
description              : &description "Personal website and portfolio of Romano Emmanuelle"   # Update this with a general description of your site, this is the default if not overridden by a page
url                      : "https://romanoemmanuelle.github.io" # The base hostname & protocol for your site
                                                           # or if you already have some other page hosted on Github then use "https://[your GitHub username].github.io/[Your Repo Name]"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "RomanoEmmanuelle/RomanoEmmanuelle.github.io"


# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : "profile.png"
  name             : "Romano Emmanuelle"
  pronouns         : # example: "she/her"  
  bio              : "Personal website and portfolio"
  location         : "Indonesia"
  employer         :
  uri              : # URL
  email            : 


  # Academic websites
  academia         : # URL
